version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  build:
    commands:
      - echo "Running build commands..."
      - echo "Build complete!"

artifacts:
  files:
    - '**/*'