---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    password: AgBJl+Grd3k5dv2Ab8KY3VINhECXBroR1tCXNbQZ/qHNb/6pZDiFLeq9l+SnJHoag/fSHof3J5dpIJzm8FwYt+znvULJY+IbBEarSFr9GD/O0NUGauirpEcWsrsY6GZlAXlyPCmRIN1TpqetPMJyU0AeDTxoH54bWD4NySJ0WRXAgMM6vtYJNRvV8NP7pmLzFQyqgH5L7jUS4acb51SqjfZr0/arQhZkRrmfXu4dARMgrqG1r3pDuV8zBIa+pulx8pRNPmFQww+awyJIdNkSR7trnto4Zili6toJLEgYTCsj82J2Q6rvKhW6QZ9s+pHY2ZPC49gWLBRzoqDVhPyuEQu3dJYtGGhPxnK71n75uCncLAf6wV9H5yiZvlDwF6rgvCKHZ/OUnvfx/bVk2SMmlp8nLHRFta4hSV/QMQjS5ZelLAGH30bj3bnnBZuwFKYveb6OKWUVib8RHSDIVF9nmPFd6veF4i7qFB5ER9JHkhYvtusvjdmMb3tiSGBwWI9oSEeyuSrepZGL3o8/IWTu5FFJRdUxbAVc4un3y2qcsrg1rL5u4VGKrtVz6DxtS8EY9IoHSvIvtAEL7snp+lNwYA2dDyDHSclqDBJKclED5tf3uCyLEun4Eo9PY9tmexCvY+VOm5FPtEZmtEJJhN3i1JSiYUmuU+B4bGNrLjdr52brV2rWX7IPMhvoVJYnFfKRdFFDTpMdUKOgCrQ9eg==
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default
