name: Apply Sealed Secret

on:
  push:
    paths:
      - 'sealed-secrets/**'
      - '.github/workflows/deploy.yml'

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config

      - name: Apply Sealed Secret
        run: kubectl apply -f sealed-secrets/mysecret.yaml
